#!/bin/bash
MIGRATIONS="${MIGRATIONS_HOME}"/*
DB_NAME="${PG_DATABASE}"
DB_USER="${PG_USER}"
while [ $# -gt 0 ]; do
    case "$1" in
        --db-name)
            shift;
            DB_NAME="$1"
            ;;
        --db-user)
            shift;
            DB_USER="$1"
            ;;
    esac
    shift
done

echo "Applying migrations to database \"${DB_NAME}\""
if [[ -z "$DB_NAME" || -z "$DB_USER" ]]; then
    echo "No db name or db user"
    exit 1
fi;

echo "FROM DIRECTORY \"${MIGRATIONS_HOME}\""
for f in $MIGRATIONS
do
    PGPASSWORD=$PG_PASSWORD psql -U $DB_USER -d $DB_NAME -a -f $f
done
exit
