version: '3'
services:
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
      args:
        - BABBLEGRAPH_GIT_TOKEN=${BABBLEGRAPH_GIT_TOKEN}
    volumes:
      - ./worker:/go/src/babblegraph/worker
    environment:
      - PG_HOST=db
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=wordsmith
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
  wordsmith:
    build:
      dockerfile: Dockerfile.dev
      context: ./wordsmith
    volumes:
      - ./wordsmith/data:/var/lib/postgresql/data
