version: '3'
services:
  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
  wordsmith:
    build:
      dockerfile: Dockerfile.dev
      context: ./wordsmith
    volumes:
      - ./wordsmith/data:/var/lib/postgresql/data
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - node.name=es01
      - cluster.name=babblegraph-es-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=http://es01,http://es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - XPACK_SECURITY_ENABLED="true"
      - ELASTIC_PASSWORD=babblegraph-dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
        - ./elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - node.name=es02
      - cluster.name=babblegraph-es-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - XPACK_SECURITY_ENABLED="true"
      - ELASTIC_PASSWORD=babblegraph-dev
    volumes:
        - ./elasticsearch/data02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./babblegraph
    volumes:
      - ./babblegraph:/usr/local/go/src/babblegraph
    environment:
      - PG_HOST=db
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=wordsmith
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
      - ES_HOSTS=es01,es02
      - ES_PASSWORD=babblegraph-dev
    command: go run /usr/local/go/src/babblegraph/services/worker/main.go
  email:
    build:
      dockerfile: Dockerfile.dev
      context: ./babblegraph
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./babblegraph:/usr/local/go/src/babblegraph
    environment:
      - PG_HOST=db
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=wordsmith
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
    command: sh
