version: '3'
services:
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./babblegraph
    volumes:
      - ./babblegraph:/usr/local/go/src/babblegraph
      - ./babblegraph/services/worker/data:/tmp
    environment:
      - PG_HOST=db
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=wordsmith
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
      - ES_HOSTS=http://es01:9200,http://es02:9200
      - ES_PASSWORD=babblegraph-dev
    command: go run /usr/local/go/src/babblegraph/services/worker/main.go
  email:
    build:
      dockerfile: Dockerfile.dev
      context: ./babblegraph
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./babblegraph:/usr/local/go/src/babblegraph
    environment:
      - PG_HOST=db
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=wordsmith
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
      - ES_HOSTS=http://es01:9200,http://es02:9200
      - ES_PASSWORD=babblegraph-dev
      - EMAIL_ADDRESS=$BABBLEGRAPH_EMAIL_ADDRESS
      - AWS_SES_ACCESS_KEY=$BABBLEGRAPH_SES_ACCESS_KEY
      - AWS_SES_SECRET_KEY=$BABBLEGRAPH_SES_ACCESS_SECRET
    command: go run /usr/local/go/src/babblegraph/services/email/main.go
