version: '3'
services:
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
      args:
        - BABBLEGRAPH_GIT_TOKEN=${BABBLEGRAPH_GIT_TOKEN}
    volumes:
      - ./worker:/go/src/babblegraph/worker
      - /go/src/babblegraph/worker/vendor
      - /go/src/babblegraph/worker/.vendor-new
    environment:
      - PG_HOST=db
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
  db:
    # TODO: use version
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
