version: '3'
services:
  task_runner:
    build:
      dockerfile: ../../../ops/babblegraph/Dockerfile.dev
      context: ./backend/src/babblegraph
    volumes:
      - ./backend/src/babblegraph:/usr/local/go/src/babblegraph
    environment:
      - PG_HOST=host.docker.internal
      - PG_PORT=5432
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=host.docker.internal
      - WORDSMITH_PORT=5433
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
      - ES_HOSTS=http://host.docker.internal:9200
      - ES_PASSWORD=babblegraph-dev
      - EMAIL_ADDRESS=$BABBLEGRAPH_EMAIL_ADDRESS
      - AWS_SES_ACCESS_KEY=$BABBLEGRAPH_SES_ACCESS_KEY
      - AWS_SES_SECRET_KEY=$BABBLEGRAPH_SES_ACCESS_SECRET
      - SENTRY_DSN=$BABBLEGRAPH_WORKER_SENTRY_DSN
      - STRIPE_KEY=$BABBLEGRAPH_STRIPE_KEY
      - AES_KEY=ryDMLNhwEqPBHMgu6YOsCZ0ihx4WgvqE
      - ENV=local
    command: go run /usr/local/go/src/babblegraph/services/taskrunner/main.go --task=user-vocabulary
