version: '3'
services:
  web:
    build:
      dockerfile: ../../../ops/babblegraph/Dockerfile.dev
      context: ./backend/src/babblegraph
    volumes:
      - ./backend/src/babblegraph:/usr/local/go/src/babblegraph
      - ./website/dist:/usr/local/go/src/babblegraph/dist
    ports:
      - 8080:8080
    environment:
      - PG_HOST=host.docker.internal
      - PG_PORT=5432
      - PG_USER=dev
      - PG_PASSWORD=development
      - PG_DB_NAME=babblegraph
      - WORDSMITH_HOST=host.docker.internal
      - WORDSMITH_PORT=5433
      - WORDSMITH_USER=dev
      - WORDSMITH_PASSWORD=development
      - WORDSMITH_DB_NAME=wordsmith
      - ES_HOSTS=http://host.docker.internal:9200
      - ES_PASSWORD=babblegraph-dev
      - ES_MIGRATION_HOSTS=http://host.docker.internal:9201
      - ES_MIGRATION_PASSWORD=babblegraph-migration-dev
      - EMAIL_ADDRESS=$BABBLEGRAPH_EMAIL_ADDRESS
      - AWS_SES_ACCESS_KEY=$BABBLEGRAPH_SES_ACCESS_KEY
      - AWS_SES_SECRET_KEY=$BABBLEGRAPH_SES_ACCESS_SECRET
      - STATIC_DIR=/usr/local/go/src/babblegraph/dist
      - AES_KEY=ryDMLNhwEqPBHMgu6YOsCZ0ihx4WgvqE
      - CAPTCHA_SECRET=$BABBLEGRAPH_CAPTCHA_SECRET
      - SENTRY_DSN=$BABBLEGRAPH_WEB_SENTRY_DSN
      - HMAC_SECRET=OsjVX9UWiXLWQ4QgkvMzh1S26XbGzkWp
      - ENV=local-no-emails
      - STRIPE_KEY=$BABBLEGRAPH_STRIPE_KEY
      - STRIPE_PUBLIC_KEY=$BABBLEGRAPH_STRIPE_PUBLIC_KEY
      - STRIPE_WEBHOOK_SECRET=$BABBLEGRAPH_STRIPE_WEBHOOK_SECRET
      - S3_KEY=$BABBLEGRAPH_SPACES_KEY
      - S3_SECRET=$BABBLEGRAPH_SPACES_SECRET
      # - LISTEN_NOTES_API_KEY=$BABBLEGRAPH_LISTEN_NOTES_API_KEY
    command: go run /usr/local/go/src/babblegraph/services/web/main.go
  frontend:
    build:
      dockerfile: ../ops/website/Dockerfile.dev
      context: ./website
    volumes:
      - ./website/dist:/usr/app/dist
      - ./website:/usr/app
