#!/bin/bash
DB_NAME="${PG_DATABASE}"
DB_USER="${PG_USER}"
while [ $# -gt 0 ]; do
    case "$1" in
        --db-name)
            shift;
            DB_NAME="$1"
            ;;
        --db-user)
            shift;
            DB_USER="$1"
            ;;
    esac
    shift
done

echo "Applying migrations"
/home/postgres/scripts/apply-migrations

echo "Applying files"
PGPASSWORD=$PG_PASSWORD psql -U $DB_USER -d $DB_NAME -a -f /home/postgres/wordsmith-data/populate_db.sql
