DEFINITIONS_TO_FILTER = {
    'da igual': ('dar igual', 'whatever'),
    'me sabe mal': ('saber mal', 'I\'m sorry'),
    'me vale': (None, None),
    'necesito papel higiénico': (None, None),
    'necesito su ayuda': (None, None),
    'necesito tu ayuda': (None, None),
    'necesito una bebida': (None, None),
    'necesito una copa': (None, None),
    'necesito un condón': (None, None),
    'necesito un diccionario': (None, None),
    'no comprendo': (None, None),
    'no entiendo': (None, None),
    'no hablo': (None, None),
    'o sea': ('o sea', 'so; therefore; in other words'),
    'por eso': ('por eso', 'therefore'),
    'por lo poco que sé': ('por lo poco que', 'for the little that (i.e. for the little that someone does)'),
    'si lo sabré yo': (None, None),
    'soy inglesa': (None, None),
    'soy inglés': (None, None),
    'te amo': (None, None),
    'te echo de menos': ('echar de menos', 'to miss someone or something'),
    'tengo calor': ('tener calor', 'to be hot'),
    'tengo una pregunta': (None, None),
    'te quiero': (None, None),
    'voy y vengo': ('ir y venir', 'to be right back'),
    'yo necesito un lápiz': (None, None),
    'yo no hablo español': (None, None),
    'yo no hablo inglés': (None, None),
    'yo no hablo turco': (None, None),
    'yo no hablo ucraniano': (None, None),
    'yo soy británica': (None, None),
    'yo soy británico': (None, None),
}
