DEFINITIONS_TO_FILTER = {
    'da igual': ('dar igual', 'whatever'),
    'me sabe mal': ('saber mal', 'I\'m sorry'),
    'me vale': (None, None),
    'necesito papel higiénico': (None, None),
    'necesito su ayuda': (None, None),
    'necesito tu ayuda': (None, None),
    'necesito una bebida': (None, None),
    'necesito una copa': (None, None),
    'necesito un condón': (None, None),
    'necesito un diccionario': (None, None),
    'no comprendo': (None, None),
    'no entiendo': (None, None),
    'no hablo': (None, None),
    'o sea': ('o sea', 'so; therefore; in other words'),
    'por eso': ('por eso', 'therefore'),
    'por lo poco que sé': ('por lo poco que', 'for the little that (i.e. for the little that someone does)'),
    'si lo sabré yo': (None, None),
    'soy inglesa': (None, None),
    'soy inglés': (None, None),
    'te amo': (None, None),
    'te echo de menos': ('echar de menos', 'to miss someone or something'),
    'tengo calor': ('tener calor', 'to be hot'),
    'tengo una pregunta': (None, None),
    'te quiero': (None, None),
    'voy y vengo': ('ir y venir', 'to be right back'),
    'yo necesito un lápiz': (None, None),
    'yo no hablo español': (None, None),
    'yo no hablo inglés': (None, None),
    'yo no hablo turco': (None, None),
    'yo no hablo ucraniano': (None, None),
    'yo soy británica': (None, None),
    'yo soy británico': (None, None),
    'beso blanco': (None, None),
    'cómo está': (None, None),
    'cómo estás': (None, None),
    'cuánto cuesta': (None, None),
    'culo del mundo': (None, None),
    'cuánto es': (None, None),
    'disfunción eréctil': (None, None),
    'dónde está el baño': (None, None),
    'dónde están los aseos': (None, None),
    'doble penetración': (None, None),
    'garganta profunda': (None, None),
    'la madre que te parió': (None, None),
    'minoría sexual': (None, None),
    'mujer fatal': (None, None),
    'necesitan ayuda': (None, None),
    'necesitas ayuda': ('necesitar ayuda', 'to need help'),
    'necesita usted ayuda': (None, None),
    'pene artificial': (None, None),
    'pene femenino': (None, None),
    'por qué no te callas': (None, None),
    'qué es eso': (None, None),
    'tomar por culo': (None, None),
    'turismo sexual': (None, None),
    'tu madre': (None, None),
    'vello púbico': (None, None),
    'vete a la mierda': (None, None),
    'vesícula seminal': (None, None),
    'vete a saber': (None, None),
    'vértebra cervical': (None, None),
    'ya que estamos': (None, None),
    'acoso sexual': (None, None),
    'agujero glorioso': (None, None),
    'bajar al pilón': (None, None),
    'cada muerte de un judío': (None, None),
}
