version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: ./deploy/web/Dockerfile
    restart: unless-stopped
    env_file: ../../env/web.env
    networks:
      - babblegraph_web_default
  proxy:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - web
    networks:
      - babblegraph_web_default
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - /etc/resolv.conf:/etc/resolv.conf
    depends_on:
      - proxy
    command: certonly --webroot --webroot-path=/var/www/html --email deaver.andrew@gmail.com --agree-tos --no-eff-email --force-renewal -d babblegraph.com -d www.babblegraph.com
    networks:
      - babblegraph_web_default

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/babblegraph/deploy/web/dhparam/
      o: bind

networks:
  babblegraph_web_default:
    driver: bridge
