package bootstrap

var ContentTopics = map[string]string{
	"art":                          "arte",
	"astronomy":                    "astronomía",
	"architecture":                 "arquitectura",
	"automotive":                   "autos",
	"business":                     "negocios",
	"celebrity-news":               "noticias de celebridades",
	"cooking":                      "cocina",
	"culture":                      "cultura",
	"current-events-argentina":     "noticias de argentina",
	"current-events-chile":         "noticias de chile",
	"current-events-colombia":      "noticias de colombia",
	"current-events-costa-rica":    "noticias de costa rica",
	"current-events-el-salvador":   "noticias de el salvador",
	"current-events-guatemala":     "noticias de guatemala",
	"current-events-honduras":      "noticias de honduras",
	"current-events-mexico":        "noticias de méxico",
	"current-events-nicaragua":     "noticias de nicaragua",
	"current-events-panama":        "noticias de panamá",
	"current-events-paraguay":      "noticias de paraguay",
	"current-events-peru":          "noticias de perú",
	"current-events-spain":         "noticias de españa",
	"current-events-united-states": "noticias de estados unidos",
	"current-events-venezuela":     "noticias de venezuela",
	"current-events-uruguay":       "noticias de uruguay",
	"current-events-puerto-rico":   "noticias de puerto rico",
	"economy":                      "economía",
	"entertainment":                "entretenimiento",
	"environment":                  "medio ambiente",
	"fashion":                      "moda",
	"film":                         "cine",
	"finance":                      "finanzas",
	"health":                       "salud",
	"home":                         "casa",
	"lifestyle":                    "estilo de vida",
	"literature":                   "literatura",
	"music":                        "música",
	"opinion":                      "opinión",
	"politics":                     "política",
	"science":                      "ciencia",
	"sports":                       "deportes",
	"technology":                   "tecnología",
	"theater":                      "teatro",
	"travel":                       "viajes",
	"video-games":                  "videojuegos",
	"world-news":                   "noticias del mundo",
}
