package bootstrap

import (
	"babblegraph/util/geo"
	"babblegraph/wordsmith"
)

type allowableDomain struct {
	Country      geo.CountryCode
	LanguageCode wordsmith.LanguageCode
	SeedURLs     []string
}

var Sources = map[string]allowableDomain{
	"ambito.com": allowableDomain{
		Country:      geo.CountryCodeArgentina,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.ambito.com/contenidos/economia.html",
			"https://www.ambito.com/contenidos/finanzas.html",
			"https://www.ambito.com/contenidos/politica.html",
			"https://www.ambito.com/contenidos/negocios.html",
			"https://www.ambito.com/contenidos/lifestyle.html",
			"https://www.ambito.com/contenidos/opinion.html",
			"https://www.ambito.com/contenidos/nacional.html",
			"https://www.ambito.com/contenidos/mundo.html",
			"https://www.ambito.com/contenidos/espectaculos.html",
			"https://www.ambito.com/contenidos/autos.html",
			"https://www.ambito.com/contenidos/deportes.html",
		},
	},
	"cronista.com": allowableDomain{
		Country:      geo.CountryCodeArgentina,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.cronista.com/apertura-negocio",
			"https://www.cronista.com/seccion/economia_politica",
			"https://www.cronista.com/seccion/finanzas_mercados",
			"https://www.cronista.com/seccion/internacionales",
			"https://www.cronista.com/seccion/columnistas",
		},
	},
	"emol.com": allowableDomain{
		Country:      geo.CountryCodeChile,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.emol.com/nacional",
			"https://www.emol.com/internacional",
			"https://www.emol.com/tecnologia",
			"https://www.emol.com/economia",
			"https://www.emol.com/deportes",
			"https://www.emol.com/espectaculos",
			"https://www.emol.com/tendencias/salud",
			"https://www.emol.com/tendencias/belleza",
			"https://www.emol.com/autos",
		},
	},
	"latercera.com": allowableDomain{
		Country:      geo.CountryCodeChile,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.latercera.com/canal/el-deportivo/",
			"https://www.latercera.com/canal/politica",
			"https://www.latercera.com/etiqueta/empresas-mercados",
			"https://www.latercera.com/etiqueta/economia-dinero",
			"https://www.latercera.com/canal/pulso",
			"https://www.latercera.com/etiqueta/practico-tecnologia/",
			"https://www.latercera.com/etiqueta/practico-belleza-y-salud/",
			"https://www.latercera.com/etiqueta/practico-casa-y-cocina/",
			"https://www.latercera.com/canal/nacional",
			"https://www.latercera.com/canal/mundo",
			"https://www.latercera.com/canal/opinion",
			"http://glamorama.latercera.com/",
			"https://www.latercera.com/etiqueta/libros",
			"https://www.latercera.com/etiqueta/musica",
			"https://www.latercera.com/etiqueta/cine/",
			"https://www.latercera.com/etiqueta/videojuegos-de-culto",
			"https://www.latercera.com/etiqueta/arte",
		},
	},
	"lacuarta.cl": allowableDomain{
		Country:      geo.CountryCodeChile,
		LanguageCode: wordsmith.LanguageCodeSpanish,
	},
	"elbogotano.com.co": allowableDomain{
		Country:      geo.CountryCodeColombia,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elbogotano.com.co/category/poder",
			"https://www.elbogotano.com.co/category/noticias",
		},
	},
	"elespectador.com": allowableDomain{
		Country:      geo.CountryCodeColombia,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elespectador.com/opinion",
			"https://www.elespectador.com/noticias/economia",
			"https://www.elespectador.com/noticias/tecnologia",
			"https://www.elespectador.com/entretenimiento",
			"https://www.elespectador.com/entretenimiento/cine",
			"https://www.elespectador.com/entretenimiento/musica",
			"https://www.elespectador.com/deportes",
			"https://www.elespectador.com/noticias/autos",
			"https://www.elespectador.com/noticias/politica",
			"https://www.elespectador.com/noticias/nacional",
			"https://www.elespectador.com/noticias/el-mundo",
			"https://www.elespectador.com/noticias/ciencia",
			"https://www.elespectador.com/noticias/salud",
		},
	},
	"elsalvador.com": allowableDomain{
		Country:      geo.CountryCodeElSalvador,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elsalvador.com/category/noticias/internacional",
			"https://www.elsalvador.com/category/noticias/nacional",
			"https://www.elsalvador.com/category/entretenimiento/espectaculos",
			"https://www.elsalvador.com/category/entretenimiento/tecnologia",
			"https://www.elsalvador.com/category/entretenimiento/turismo",
			"https://www.elsalvador.com/category/entretenimiento/cultura",
			"https://www.elsalvador.com/category/vida/salud",
			"https://www.elsalvador.com/category/deportes",
			"https://www.elsalvador.com/category/opinion",
		},
	},
	"elmundo.sv": allowableDomain{
		Country:      geo.CountryCodeElSalvador,
		LanguageCode: wordsmith.LanguageCodeSpanish,
	},
	"dca.gob.gt": allowableDomain{
		Country:      geo.CountryCodeGuatemala,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/nacionales",
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/opinion",
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/deportes",
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/artes",
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/economicas",
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/internacionales/",
			"https://dca.gob.gt/noticias-guatemala-diario-centro-america/category/salud/",
		},
	},
	"prensalibre.com": allowableDomain{
		Country:      geo.CountryCodeGuatemala,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.prensalibre.com/guatemala",
			"https://www.prensalibre.com/deportes",
			"https://www.prensalibre.com/internacional",
			"https://www.prensalibre.com/economia",
			"https://www.prensalibre.com/vida",
			"https://www.prensalibre.com/opinion",
			"https://www.prensalibre.com/vida/tecnologia/",
			"https://www.prensalibre.com/vida/salud-y-familia/",
		},
	},
	"heraldodemexico.com.mx": allowableDomain{
		Country:      geo.CountryCodeMexico,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://heraldodemexico.com.mx/nacional",
			"https://heraldodemexico.com.mx/mundo/",
			"https://heraldodemexico.com.mx/economia/",
			"https://heraldodemexico.com.mx/espectaculos/",
			"https://heraldodemexico.com.mx/temas/viajes-1865.html",
			"https://heraldodemexico.com.mx/temas/autos-1868.html",
			"https://heraldodemexico.com.mx/cultura/",
			"https://heraldodemexico.com.mx/tecnologia/",
		},
	},
	"eleconomista.com.mx": allowableDomain{
		Country:      geo.CountryCodeMexico,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.eleconomista.com.mx/seccion/empresas/",
			"https://www.eleconomista.com.mx/seccion/sector-financiero/",
			"https://www.eleconomista.com.mx/seccion/internacionales/",
			"https://www.eleconomista.com.mx/seccion/tecnologia/",
			"https://www.eleconomista.com.mx/seccion/opinion/",
			"https://www.eleconomista.com.mx/seccion/arte-ideas/",
			"https://www.eleconomista.com.mx/seccion/economia/",
			"https://www.eleconomista.com.mx/seccion/politica/",
			"https://www.eleconomista.com.mx/seccion/deportes/",
		},
	},
	"yucatan.com.mx": allowableDomain{
		Country:      geo.CountryCodeMexico,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.yucatan.com.mx/seccion/mexico",
			"https://www.yucatan.com.mx/seccion/internacional",
			"https://www.yucatan.com.mx/seccion/deportes",
			"https://www.yucatan.com.mx/seccion/espectaculos",
			"https://www.yucatan.com.mx/seccion/merida",
			"https://www.yucatan.com.mx/seccion/yucatan",
		},
	},
	"informador.mx": allowableDomain{
		Country:      geo.CountryCodeMexico,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.informador.mx/seccion/jalisco/",
			"https://www.informador.mx/seccion/mexico/",
			"https://www.informador.mx/seccion/internacional/",
			"https://www.informador.mx/seccion/deportes/",
			"https://www.informador.mx/seccion/entretenimiento/",
			"https://www.informador.mx/autos-t2294",
			"https://www.informador.mx/seccion/economia/",
			"https://www.informador.mx/seccion/tecnologia/",
			"https://www.informador.mx/seccion/cultura/",
		},
	},
	"laprensa.com.ni": allowableDomain{
		Country:      geo.CountryCodeNicaragua,
		LanguageCode: wordsmith.LanguageCodeSpanish,
	},
	"lajornadanet.com": allowableDomain{
		Country:      geo.CountryCodeNicaragua,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.lajornadanet.com/index.php/noticias/nicaragua",
			"https://www.lajornadanet.com/index.php/noticias/nicaragua/politica",
			"https://www.lajornadanet.com/index.php/noticias/empresariales/",
			"https://www.lajornadanet.com/index.php/noticias/economia/",
			"https://www.lajornadanet.com/index.php/noticias/mundo/",
			"https://www.lajornadanet.com/index.php/noticias/ciencia/",
			"https://www.lajornadanet.com/index.php/noticias/mexico/",
			"https://www.lajornadanet.com/index.php/noticias/costa-rica/",
			"https://www.lajornadanet.com/index.php/noticias/tecno/",
		},
	},
	"elsiglo.com": allowableDomain{
		Country:      geo.CountryCodePanama,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"http://elsiglo.com.pa/tag/panama/13",
			"http://elsiglo.com.pa/tag/internacional/17",
			"http://elsiglo.com.pa/tag/economia/18",
			"http://elsiglo.com.pa/tag/deportes/19",
			"http://elsiglo.com.pa/tag/espectaculos/20",
			"http://elsiglo.com.pa/tag/opinion/22",
		},
	},
	"larepublica.pe": allowableDomain{
		Country:      geo.CountryCodePeru,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://larepublica.pe/politica/",
			"https://larepublica.pe/economia/",
			"https://larepublica.pe/mundo/",
			"https://larepublica.pe/deportes/",
			"https://larepublica.pe/salud/",
			"https://larepublica.pe/cultural/",
			"https://larepublica.pe/ciencia/",
			"https://larepublica.pe/turismo/",
			"https://larepublica.pe/espectaculos/",
			"https://larepublica.pe/tecnologia/",
			"https://larepublica.pe/cine-series/",
			"https://larepublica.pe/videojuegos/",
			"https://larepublica.pe/estilo/",
			"https://larepublica.pe/region-norte/",
			"https://larepublica.pe/region-sur/",
		},
	},
	"abc.com.py": allowableDomain{
		Country:      geo.CountryCodeParaguay,
		LanguageCode: wordsmith.LanguageCodeSpanish,
	},
	"ultimahora.com": allowableDomain{
		Country:      geo.CountryCodeParaguay,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.ultimahora.com/contenidos/nacional.html",
			"https://d10.ultimahora.com/",
			"https://tvo.ultimahora.com/",
			"https://www.ultimahora.com/contenidos/gaming.html",
			"https://www.ultimahora.com/contenidos/arte-y-espectaculos.html",
			"https://www.ultimahora.com/contenidos/mundo.html",
			"https://www.ultimahora.com/contenidos/turismo.html",
		},
	},
	"abc.es": allowableDomain{
		Country:      geo.CountryCodeSpain,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.abc.com.py/nacionales",
			"https://www.abc.com.py/deportes",
			"https://www.abc.com.py/espectaculos",
			"https://www.abc.com.py/internacionales",
		},
	},
	"elmundo.es": allowableDomain{
		Country:      geo.CountryCodeSpain,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elmundo.es/espana.html",
			"https://www.elmundo.es/opinion.html",
			"https://www.elmundo.es/economia.html",
			"https://www.elmundo.es/internacional.html",
			"https://www.elmundo.es/deportes.html",
			"https://www.elmundo.es/cultura/cine.html",
			"https://www.elmundo.es/cultura/literatura.html",
			"https://www.elmundo.es/cultura/musica.html",
			"https://www.elmundo.es/cultura/teatro.html",
			"https://www.elmundo.es/cultura/arte.html",
			"https://www.elmundo.es/ciencia-y-salud/ciencia.html",
			"https://www.elmundo.es/ciencia-y-salud/salud.html",
			"https://www.elmundo.es/tecnologia.html",
			"https://www.elmundo.es/tecnologia/videojuegos.html",
		},
	},
	"elpais.com": allowableDomain{
		Country:      geo.CountryCodeSpain,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://elpais.com/internacional/",
			"https://elpais.com/opinion/",
			"https://elpais.com/espana/",
			"https://elpais.com/ciencia/",
			"https://elpais.com/tecnologia/",
			"https://elpais.com/noticias/libros/",
			"https://elpais.com/noticias/cine/",
			"https://elpais.com/noticias/musica/",
			"https://elpais.com/noticias/teatro/",
			"https://elpais.com/noticias/arte/",
			"https://elpais.com/noticias/arquitectura/",
			"https://elpais.com/deportes/",
			"https://motor.elpais.com/",
			"https://elviajero.elpais.com/",
			"https://elpais.com/economia/negocios/",
		},
	},
	"elpais.com.uy": allowableDomain{
		Country:      geo.CountryCodeUruguay,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elpais.com.uy/mundo",
			"https://www.elpais.com.uy/opinion",
			"https://www.elpais.com.uy/negocios",
			"https://www.elpais.com.uy/ovacion",
		},
	},
	"elcomercio.es": allowableDomain{
		Country:      geo.CountryCodeSpain,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elcomercio.es/asturias/",
			"https://www.elcomercio.es/politica/",
			"https://www.elcomercio.es/internacional/",
			"https://www.elcomercio.es/economia/",
			"https://www.elcomercio.es/deportes/",
			"https://www.elcomercio.es/culturas/cine/",
			"https://www.elcomercio.es/culturas/libros/",
			"https://www.elcomercio.es/culturas/arte/",
			"https://www.elcomercio.es/culturas/musica/",
		},
	},
	"diariolasamericas.com": allowableDomain{
		Country:      geo.CountryCodeUnitedStates,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.diariolasamericas.com/contenidos/mundo.html",
			"https://www.diariolasamericas.com/contenidos/eeuu.html",
			"https://www.diariolasamericas.com/contenidos/deportes.html",
			"https://www.diariolasamericas.com/contenidos/cultura.html",
			"https://www.diariolasamericas.com/contenidos/opini%C3%B3n.html",
			"https://www.diariolasamericas.com/contenidos/tecnologia.html",
			"https://www.diariolasamericas.com/contenidos/economia.html",
		},
	},
	"laopinion.com": allowableDomain{
		Country:      geo.CountryCodeUnitedStates,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://laopinion.com/categoria/entretenimiento/",
			"https://laopinion.com/categoria/deportes/",
			"https://laopinion.com/categoria/autos/",
			"https://laopinion.com/categoria/estilo/",
			"https://laopinion.com/categoria/dinero/",
			"https://laopinion.com/categoria/tecnologia/",
			"https://laopinion.com/categoria/opinion/",
			"https://laopinion.com/categoria-guia-de-compras/salud/",
			"https://laopinion.com/categoria-guia-de-compras/tecnologia/",
			"https://laopinion.com/categoria-guia-de-compras/ropa-y-accesorios/",
		},
	},
	"eldiariony.com": allowableDomain{
		Country:      geo.CountryCodeUnitedStates,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://eldiariony.com/categoria/entretenimiento/",
			"https://eldiariony.com/categoria/deportes/",
			"https://eldiariony.com/categoria/salud/",
			"https://eldiariony.com/categoria/comida/",
			"https://eldiariony.com/categoria/estilo/",
			"https://eldiariony.com/categoria/dinero/",
			"https://eldiariony.com/categoria/tecnologia/",
			"https://eldiariony.com/categoria/opinion/",
		},
	},
	"hoylosangeles.com": allowableDomain{
		Country:      geo.CountryCodeUnitedStates,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.hoylosangeles.com/espectaculos/musica",
			"https://www.hoylosangeles.com/espectaculos/cine",
			"https://www.hoylosangeles.com/espectaculos",
			"https://www.hoylosangeles.com/deportes",
			"https://www.hoylosangeles.com/vidayestilo/salud",
			"https://www.hoylosangeles.com/vidayestilo/cienciaytecnologia",
			"https://www.hoylosangeles.com/vidayestilo/viajes",
			"https://www.hoylosangeles.com/vidayestilo/autos",
			"https://www.hoylosangeles.com/vidayestilo/cocina",
			"https://www.hoylosangeles.com/vidayestilo/libros",
			"https://www.hoylosangeles.com/opinion",
			"https://www.hoylosangeles.com/noticias/estadosunidos",
		},
	},
	"elnacional.com": allowableDomain{
		Country:      geo.CountryCodeVenezuela,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.elnacional.com/venezuela/",
			"https://www.elnacional.com/mundo/",
			"https://www.elnacional.com/economia/",
			"https://www.elnacional.com/deportes/",
			"https://www.elnacional.com/salud-ciencia-tecnologia",
			"https://www.elnacional.com/gamers",
			"https://www.elnacional.com/gadgets",
			"https://www.elnacional.com/cine",
			"https://www.elnacional.com/literatura",
			"https://www.elnacional.com/musica",
			"https://www.elnacional.com/teatro",
			"https://www.elnacional.com/opinion/",
			"https://www.elnacional.com/gastronomia",
			"https://www.elnacional.com/moda",
			"https://www.elnacional.com/viajes-turismo",
		},
	},
	"eldiario.com": allowableDomain{
		Country:      geo.CountryCodeVenezuela,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://eldiario.com/seccion/politica/",
			"https://eldiario.com/seccion/economia/",
			"https://eldiario.com/seccion/venezuela/",
			"https://eldiario.com/seccion/mundo/",
			"https://eldiario.com/seccion/deportes/",
			"https://eldiario.com/seccion/cultura/",
			"https://eldiario.com/seccion/tecnologia/",
		},
	},
	"brecha.com.uy": allowableDomain{
		Country:      geo.CountryCodeUruguay,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://brecha.com.uy/category/politica/",
			"https://brecha.com.uy/category/cultura/",
			"https://brecha.com.uy/category/mundo/",
			"https://brecha.com.uy/category/columnas-de-opinion/",
		},
	},
	"ladiaria.com.uy": allowableDomain{
		Country:      geo.CountryCodeUruguay,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://ladiaria.com.uy/seccion/politica-nacional/",
			"https://ladiaria.com.uy/seccion/politica-internacional/",
			"https://ladiaria.com.uy/opinion/",
			"https://ladiaria.com.uy/seccion/arte/",
			"https://ladiaria.com.uy/seccion/cine-tv-streaming/",
			"https://ladiaria.com.uy/seccion/teatro/",
			"https://ladiaria.com.uy/seccion/musica/",
			"https://ladiaria.com.uy/seccion/videojuegos/",
			"https://ladiaria.com.uy/seccion/casa/",
			"https://ladiaria.com.uy/seccion/comer-y-beber/",
			"https://ladiaria.com.uy/seccion/tecnologia/",
			"https://ladiaria.com.uy/seccion/turismo/",
			"https://ladiaria.com.uy/seccion/vida-saludable/",
			"https://ladiaria.com.uy/deporte/",
			"https://ladiaria.com.uy/ciencia/",
			"https://ladiaria.com.uy/economia/",
			"https://ladiaria.com.uy/salud/",
		},
	},
	"ngenespanol.com": allowableDomain{
		Country:      geo.CountryCodeUnitedStates,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.ngenespanol.com/traveler/",
			"https://www.ngenespanol.com/animales/",
			"https://www.ngenespanol.com/el-mundo/",
			"https://www.ngenespanol.com/el-espacio/",
			"https://www.ngenespanol.com/ciencia/",
		},
	},
	"primerahora.com": allowableDomain{
		Country:      geo.CountryCodePuertoRico,
		LanguageCode: wordsmith.LanguageCodeSpanish,
		SeedURLs: []string{
			"https://www.primerahora.com/noticias/puerto-rico/",
			"https://www.primerahora.com/noticias/policia-tribunales/",
			"https://www.primerahora.com/noticias/gobierno-politica/",
			"https://www.primerahora.com/noticias/consumo/",
			"https://www.primerahora.com/noticias/estados-unidos/",
			"https://www.primerahora.com/noticias/mundo/",
			"https://www.primerahora.com/noticias/ciencia-tecnologia/",
			"https://www.primerahora.com/entretenimiento/farandula/",
			"https://www.primerahora.com/entretenimiento/musica/",
			"https://www.primerahora.com/entretenimiento/cine-tv/",
			"https://www.primerahora.com/entretenimiento/cultura-teatro/",
			"https://www.primerahora.com/entretenimiento/otras/",
			"https://www.primerahora.com/deportes/baloncesto/",
			"https://www.primerahora.com/deportes/beisbol/",
			"https://www.primerahora.com/deportes/boxeo/",
			"https://www.primerahora.com/deportes/voleibol/",
			"https://www.primerahora.com/deportes/hipismo/",
			"https://www.primerahora.com/deportes/otros/",
			"https://www.primerahora.com/estilos-de-vida/ph-mas-saludable/",
			"https://www.primerahora.com/estilos-de-vida/cocina/",
			"https://www.primerahora.com/estilos-de-vida/moda-estilo/",
		},
	},
}
