#!/bin/bash
MIGRATIONS=./db/migrations/*
DOCKER_DB='babblegraph_db_1'
while [ $# -gt 0 ]; do
    case "$1" in
        --db)
            shift;
            DOCKER_DB="$1"
            ;;
        --db-name)
            shift;
            DB_NAME="$1"
            ;;
        --db-user)
            shift;
            DB_USER="$1"
            ;;
    esac
    shift
done

if [[ -z "$DB_NAME" || -z "$DB_USER" ]]; then
    echo "No db name or db user"
    exit 1
fi;

for f in $MIGRATIONS
do
    docker exec -it $DOCKER_DB psql -U $DB_USER -d $DB_NAME -c "$(cat $f)"
done
exit
