#!/bin/bash
set -euo pipefail

echo "Building..."
docker build \
    --network=host \
    -f deploy/elasticsearch/Dockerfile \
    -t babblegraph.com/elasticsearch:$(git rev-parse --short HEAD) \
    ./deploy/elasticsearch

echo "Removing old container..."
docker stop babblegraph_elasticsearch && docker rm babblegraph_elasticsearch && true

echo "Running new container..."
docker run -d -v $(pwd)/deploy/elasticsearch/data:/usr/share/elasticsearch/data \
    -v $(pwd)/deploy/elasticsearch/log:/usr/share/elasticsearch/log \
    -v $(pwd)/deploy/elasticsearch/lib:/usr/share/elasticsearch/lib \
    -v $(pwd)/deploy/elasticsearch/scripts:/elasticsearch/scripts \
    --network=host \
    --env-file ./env/elasticsearch.env \
    --restart unless-stopped \
    --name babblegraph_elasticsearch \
    babblegraph.com/elasticsearch:$(git rev-parse --short HEAD)
