#!/bin/bash
set -euo pipefail

echo "Building..."
docker build \
    -f babblegraph/Dockerfile.worker \
    -t babblegraph.com/worker:$(git rev-parse --short HEAD) \
    ./babblegraph

echo "Removing old container..."
docker stop babblegraph_worker && docker rm babblegraph_worker && true

echo "Running new container..."
docker run -d -v $(pwd)/worker/data:/tmp \
    --env-file ./env/worker.env \
    --restart unless-stopped \
    --name babblegraph_worker \
    babblegraph.com/worker:$(git rev-parse --short HEAD)
