#!/bin/bash
set -euo pipefail

echo "Building..."
docker build \
    -f deploy/worker/Dockerfile \
    -t babblegraph.com/worker:$(git rev-parse --short HEAD) \
    ./backend/src/babblegraph

echo "Removing old container..."
docker stop babblegraph_worker && docker rm babblegraph_worker && true

echo "Running new container..."
docker run -d \
    --env-file ./env/worker.env \
    --restart unless-stopped \
    --name babblegraph_worker \
    babblegraph.com/worker:$(git rev-parse --short HEAD)
