#!/bin/bash
set -euo pipefail

docker-compose -f ops/local-dbs.compose.yaml up --build -d

until (docker exec ops_wordsmith_1 psql -U dev -d wordsmith -c 'SELECT * FROM word_bigram_counts'); do
    echo "Waiting for container to be up"
    sleep 1;
done;

echo "Applying file"
docker exec ops_wordsmith_1 psql -U dev -d wordsmith -a -f /home/postgres/wordsmith-data/populate_db.sql
