#!/bin/bash
docker build -f ops/babblegraph/Dockerfile.test -t babblegraph/test ./backend/src/babblegraph
docker run -e AES_KEY ryDMLNhwEqPBHMgu6YOsCZ0ihx4WgvqE -v $(pwd)/backend/src/babblegraph:/usr/local/go/src/babblegraph babblegraph/test
