#!/bin/bash
DB_NAME="${PG_DATABASE}"
DB_USER="${PG_USER}"
while [ $# -gt 0 ]; do
    case "$1" in
        --url)
            shift;
            URL="$1"
            ;;
        --db-name)
            shift;
            DB_NAME="$1"
            ;;
        --db-user)
            shift;
            DB_USER="$1"
            ;;
    esac
    shift
done

if [[ -z "$URL" || -z "$DB_NAME" || -z "$DB_USER" ]]; then
    echo "No domain, url, db name, or db user"
    exit 1
fi;
PGPASSWORD=$PG_PASSWORD psql -U $DB_USER -d $DB_NAME -c "INSERT INTO queue_messages (topic, body) VALUES ('fetch-queue-topic', '{\"url\":\"$URL\"}')"
exit
