#!/bin/bash
DB_NAME="${PG_DATABASE}"
DB_USER="${PG_USER}"
while [ $# -gt 0 ]; do
    case "$1" in
        --email)
            shift;
            EMAIL="$1"
            ;;
        --db-name)
            shift;
            DB_NAME="$1"
            ;;
        --db-user)
            shift;
            DB_USER="$1"
            ;;
    esac
    shift
done

if [[ -z "$EMAIL" || -z "$DB_NAME" || -z "$DB_USER" ]]; then
    echo "No email, db name, or db user"
    exit 1
fi;

PGPASSWORD=$PG_PASSWORD psql -U $DB_USER -d $DB_NAME -c "INSERT INTO users (email_address, status) VALUES ('$EMAIL', 'verified')"
exit
