version: '3'
services:
  db:
    build:
      dockerfile: ../../ops/main-db/Dockerfile.dev
      context: ../deploy/main-db
    volumes:
      - ../deploy/main-db/data:/var/lib/postgresql/data
      - ../deploy/main-db/migrations:/home/postgres/migrations
      - ../deploy/main-db/scripts:/home/postgres/scripts
    ports:
      - 5432:5432
    environment:
      - MIGRATIONS_HOME=/home/postgres/migrations
  wordsmith:
    build:
      dockerfile: ../../ops/wordsmith/Dockerfile.dev
      context: ../deploy/wordsmith
    volumes:
      - ../deploy/wordsmith/data:/var/lib/postgresql/data
      - ./wordsmith/setup/out:/home/postgres/wordsmith-data
      - ../deploy/wordsmith/migrations:/home/postgres/migrations
      - ../deploy/wordsmith/scripts:/home/postgres/scripts
    environment:
      - MIGRATIONS_HOME=/home/postgres/migrations
    ports:
      - 5433:5432
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - node.name=es01
      - cluster.name=babblegraph-es-cluster-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=babblegraph-dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
        - ./elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
