version: '3'
services:
  db:
    build:
      dockerfile: ../../ops/main-db/Dockerfile.dev
      context: ../deploy/main-db
    volumes:
      - ../deploy/main-db/data:/var/lib/postgresql/data
      - ../deploy/main-db/migrations:/home/postgres/migrations
      - ../deploy/main-db/scripts:/home/postgres/scripts
    ports:
      - 5432:5432
    environment:
      - MIGRATIONS_HOME=/home/postgres/migrations
  wordsmith:
    build:
      dockerfile: ../../ops/wordsmith/Dockerfile.dev
      context: ../deploy/wordsmith
    volumes:
      - ../deploy/wordsmith/data:/var/lib/postgresql/data
      - ./wordsmith/setup/out:/home/postgres/wordsmith-data
    ports:
      - 5433:5432
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - node.name=es01
      - cluster.name=babblegraph-es-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - XPACK_SECURITY_ENABLED="true"
      - ELASTIC_PASSWORD=babblegraph-dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
        - ./elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - node.name=es02
      - cluster.name=babblegraph-es-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - XPACK_SECURITY_ENABLED="true"
      - ELASTIC_PASSWORD=babblegraph-dev
    volumes:
        - ./elasticsearch/data02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
