#!/bin/bash
FILE_NAME="prod_babblegraph_data_$(date +"%Y_%m_%d_%H_%M")"
curl -X PUT --user $ES_USERNAME:$ES_PASSWORD -k -H "Content-Type: application/json" -d @"${BABBLEGRAPH_DIR}/deploy/elasticsearch/scripts/capture-snapshot-request.json" http://localhost:9200/_snapshot/prod_babblegraph_data_snapshots/$FILE_NAME
