#!/bin/bash
curl -X PUT --user $ES_USERNAME:$ES_PASSWORD -k -H "Content-Type: application/json" -d @$(pwd)/deploy/elasticsearch/scripts/snapshot-request.json http://localhost:9200/_snapshot/prod_babblegraph_data_snapshots
