#!/bin/bash
echo "Installing plugin"
docker exec -it babblegraph_elasticsearch elasticsearch/bin/elasticsearch-plugin install repository-s3

echo "Setting up repostiory"
docker exec -it babblegraph_elasticsearch /bin/bash -c "echo $AWS_ACCESS_KEY_ID | /elasticsearch/bin/elasticsearch-keystore add --stdin s3.client.default.access_key"
docker exec -it babblegraph_elasticsearch /bin/bash -c "echo $AWS_SECRET_ACCESS_KEY | /elasticsearch/bin/elasticsearch-keystore add --stdin s3.client.default.secret_key"
