#!/bin/bash
/elasticsearch/bin/elasticsearch-keystore create -p
echo $AWS_ACCESS_KEY_ID | /elasticsearch/bin/elasticsearch-keystore add --stdin s3.client.default.access_key
echo $AWS_SECRET_ACCESS_KEY | /elasticsearch/bin/elasticsearch-keystore add --stdin s3.client.default.secret_key
